# Generated by Django 6.1 on 2026-08-20 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('local', models.TextField(verbose_name='Localização / Endereço')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário Início (24h)')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Horário Fim (24h)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='PresencaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_presentes', models.IntegerField(default=0, verbose_name='Dias Presentes')),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGO', 'Pago')], default='PENDENTE', max_length=20, verbose_name='Status Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago (R$)')),
                ('data_pagamento', models.DateTimeField(auto_now=True, verbose_name='Data do Pagamento')),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presenca_pagamento', to='eventos.candidatura')),
            ],
            options={
                'verbose_name': 'Presença e Pagamento',
                'verbose_name_plural': 'Presenças e Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função / Cargo')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Diária (R$)')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade de Vagas')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PREENCHIDA', 'Preenchida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='eventos.vaga'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together={('vaga', 'usuario')},
        ),
    ]
