# Generated by Django 6.1 on 2026-08-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='evento',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='lat_checkin',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude Check-in'),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='lng_checkin',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude Check-in'),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='status_deslocamento',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('A_CAMINHO', 'A Caminho'), ('NO_LOCAL', 'No Local / Check-in Realizado')], default='AGUARDANDO', max_length=20, verbose_name='Status Deslocamento'),
        ),
    ]
