# Generated by Django 6.1 on 2026-08-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_latitude_evento_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='dress_code',
            field=models.TextField(blank=True, null=True, verbose_name='Dress Code / Uniforme Exigido'),
        ),
    ]
