# Generated by Django 6.1 on 2026-08-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_dress_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencapagamento',
            name='ultima_data_checkin',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Último Check-in'),
        ),
    ]
