# Generated by Django 6.1 on 2026-08-24 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chamadosuporte_options_alter_empresa_options_and_more'),
        ('eventos', '0004_presencapagamento_ultima_data_checkin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatura',
            options={},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='presencapagamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vaga',
            options={},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='data_pagamento',
        ),
        migrations.AddField(
            model_name='vaga',
            name='prazo_pagamento_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dress_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='dias_presentes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='lat_checkin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='lng_checkin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='status_deslocamento',
            field=models.CharField(default='NAO_INICIADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='status_pagamento',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='ultima_data_checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='funcao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(default='ABERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
