# Generated by Django 6.1 on 2026-08-25 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_inscricao_municipal_empresa_nfse_ambiente_and_more'),
        ('eventos', '0005_alter_candidatura_options_alter_evento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data_fim',
            new_name='data_termino',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='ultima_data_checkin',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='data_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='nfse_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da NFS-e'),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='nfse_pdf_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link PDF da Nota'),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='nfse_status',
            field=models.CharField(choices=[('NAO_EMITIDA', 'Não Emitida'), ('PROCESSANDO', 'Processando'), ('EMITIDA', 'Emitida'), ('ERRO', 'Erro na Emissão')], default='NAO_EMITIDA', max_length=30),
        ),
        migrations.AddField(
            model_name='vaga',
            name='dress_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dress_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='dias_presentes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='status_deslocamento',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando'), ('A_CAMINHO', 'A Caminho'), ('CHECKIN_REALIZADO', 'Check-in Realizado'), ('VALIDADO', 'Validado Presencial'), ('FALTOU', 'Faltou')], default='PENDENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CONFIRMADO', 'Confirmado pelo Staff'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('PREENCHIDA', 'Preenchida')], default='ABERTA', max_length=20),
        ),
    ]
