# Generated by Django 6.1 on 2026-08-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_rename_data_fim_evento_data_termino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='aceitou_termo',
            field=models.BooleanField(default=False, verbose_name='Aceitou Contrato e Termo de Imagem'),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='data_aceite_termo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='orcamento_previsto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Orçamento Previsto (R$)'),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='comentario_desempenho',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário de Avaliação'),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='nota_desempenho',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nota (1 a 5 estrelas)'),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='nfse_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='nfse_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='nfse_status',
            field=models.CharField(default='NAO_EMITIDA', max_length=30),
        ),
        migrations.CreateModel(
            name='AvisoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='eventos.evento')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
