# Generated by Django 6.1 on 2026-08-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_candidatura_aceitou_termo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencapagamento',
            name='foto_checkin',
            field=models.ImageField(blank=True, null=True, upload_to='checkins/', verbose_name='Selfie de Check-in'),
        ),
    ]
