# Generated by Django 6.1 on 2026-08-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_inscricao_municipal_empresa_nfse_ambiente_and_more'),
        ('eventos', '0008_presencapagamento_foto_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presencapagamento',
            name='nfse_numero',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='nfse_pdf_url',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='nfse_status',
        ),
        migrations.CreateModel(
            name='PropostaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Razão Social / Nome do Cliente')),
                ('cliente_cnpj_cpf', models.CharField(max_length=20, verbose_name='CNPJ / CPF do Cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cliente_endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total da Proposta (R$)')),
                ('descricao_servicos', models.TextField(verbose_name='Descrição dos Serviços')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='RASCUNHO', max_length=20)),
                ('nfse_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('nfse_status', models.CharField(choices=[('NAO_EMITIDA', 'Não Emitida'), ('EMITIDA', 'Emitida'), ('ERRO', 'Erro na Emissão')], default='NAO_EMITIDA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='core.empresa')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='eventos.evento')),
            ],
        ),
    ]
