# Generated by Django 6.1 on 2026-08-31 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_remove_presencapagamento_nfse_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisoevento',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='dress_code',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='data_checkin',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='dias_presentes',
        ),
        migrations.AddField(
            model_name='evento',
            name='token_cliente',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='credencial_entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='equipamento_devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='radio_entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='uniforme_entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='avisoevento',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='aceitou_termo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='orcamento_previsto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='comentario_desempenho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='foto_checkin',
            field=models.ImageField(blank=True, null=True, upload_to='checkins/'),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='nota_desempenho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='status_deslocamento',
            field=models.CharField(default='AGUARDANDO', max_length=30),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='status_pagamento',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='cliente_cnpj_cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='cliente_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='descricao_servicos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='nfse_status',
            field=models.CharField(default='NAO_EMITIDA', max_length=20),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='status',
            field=models.CharField(default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='funcao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(default='ABERTA', max_length=20),
        ),
    ]
