# Generated by Django 6.1 on 2026-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_alter_avisoevento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Análise'), ('APROVADO_CLIENTE', 'Aprovado pelo Cliente'), ('APROVADO', 'Validado pela Produtora'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=30),
        ),
    ]
