# Generated by Django 6.1 on 2026-09-01 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_alter_candidatura_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presencapagamento',
            old_name='lat_checkin',
            new_name='latitude_checkin',
        ),
        migrations.RenameField(
            model_name='presencapagamento',
            old_name='lng_checkin',
            new_name='longitude_checkin',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(default='ATIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='checkin_fora_do_raio',
            field=models.BooleanField(default=False, verbose_name='Fora do Raio (>200m)'),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='checkin_horario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='comprovante_pix',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pix/'),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='distancia_checkin_m',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distância do Local (m)'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='orcamento_previsto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='status',
            field=models.CharField(default='ENVIADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
