# Generated by Django 6.1 on 2026-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_rename_lat_checkin_presencapagamento_latitude_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='ip_aceite_termo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='user_agent_aceite_termo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
