# Generated by Django 6.1 on 2026-09-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_candidatura_ip_aceite_termo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencapagamento',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presencapagamento',
            name='transacao_pix_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transação / E2E PIX'),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Em Processamento'), ('PAGO', 'Pago / Quitado'), ('CANCELADO', 'Cancelado / Faltou')], default='PENDENTE', max_length=20),
        ),
    ]
