# Generated by Django 6.1 on 2026-09-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_presencapagamento_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='codigo_acesso_cliente',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código/PIN de Acesso do Cliente'),
        ),
    ]
