# Generated by Django 6.1 on 2026-09-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_evento_codigo_acesso_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='prazo_pagamento_dias',
            field=models.IntegerField(default=0, help_text='Prazo em dias após o evento para realizar o pagamento'),
        ),
    ]
