# Generated by Django 6.1 on 2026-09-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_alter_vaga_prazo_pagamento_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Início'),
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Término'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_especifica_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início da Vaga'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_especifica_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data Término da Vaga'),
        ),
    ]
