# Generated by Django 6.1 on 2026-09-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_evento_horario_inicio_evento_horario_termino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presencapagamento',
            name='comentario_desempenho',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='comprovante_pix',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='credencial_entregue',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='equipamento_devolvido',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='foto_checkin',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='nota_desempenho',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='radio_entregue',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='status_deslocamento',
        ),
        migrations.RemoveField(
            model_name='presencapagamento',
            name='uniforme_entregue',
        ),
        migrations.RemoveField(
            model_name='propostacomercial',
            name='cliente_endereco',
        ),
        migrations.RemoveField(
            model_name='propostacomercial',
            name='nfse_numero',
        ),
        migrations.RemoveField(
            model_name='propostacomercial',
            name='nfse_status',
        ),
        migrations.AddField(
            model_name='vaga',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Entrada do Staff'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='horario_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Saída do Staff'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Início do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Término do Evento'),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='checkin_fora_do_raio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='distancia_checkin_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presencapagamento',
            name='transacao_pix_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='data_especifica_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='data_especifica_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='prazo_pagamento_dias',
            field=models.IntegerField(default=0),
        ),
    ]
