# Generated by Django 6.1 on 2026-08-20 18:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Razão Social / Nome Fantasia')),
                ('cnpj', models.CharField(max_length=30, unique=True, verbose_name='CNPJ ou CPF')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual')),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix da Empresa')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INADIMPLENTE', 'Inadimplente'), ('DEGUSTACAO', 'Degustação'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=20)),
                ('plano', models.CharField(default='MENSAL', max_length=50)),
                ('valor_plano', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa / Produtora',
                'verbose_name_plural': 'Empresas / Produtoras',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin SaaS'), ('ADMIN', 'Admin Produtora'), ('STAFF', 'Staff / Colaborador')], default='SUPER_ADMIN', max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro / Não Informar')], max_length=1, null=True, verbose_name='Gênero')),
                ('tamanho_camiseta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tamanho de Camiseta')),
                ('tamanho_calcado', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Calçado')),
                ('tipo_chave_pix', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('ALEATORIA', 'Chave Aleatória')], max_length=20, null=True, verbose_name='Tipo da Chave Pix')),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('nota_media', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
