# Generated by Django 6.1 on 2026-08-20 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chamado de Suporte',
                'verbose_name_plural': 'Chamados de Suporte',
            },
        ),
        migrations.CreateModel(
            name='MensagemChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.chamadosuporte')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem de Chamado',
                'verbose_name_plural': 'Mensagens de Chamados',
            },
        ),
    ]
