# Generated by Django 6.1 on 2026-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chamadosuporte_mensagemchamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp da Empresa'),
        ),
    ]
