# Generated by Django 6.1 on 2026-08-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chamadosuporte_options_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nfse_ambiente',
            field=models.CharField(choices=[('HOMOLOGACAO', 'Homologação'), ('PRODUCAO', 'Produção')], default='HOMOLOGACAO', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nfse_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave API NFS-e'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp_api_instancia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instância WhatsApp API'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp_api_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token WhatsApp API'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp_disparos_mes',
            field=models.IntegerField(default=0, verbose_name='Disparos Realizados no Mês'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='plano',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('PREMIUM', 'Premium')], default='BASICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=20),
        ),
    ]
