# Generated by Django 6.1 on 2026-08-31 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_inscricao_municipal_empresa_nfse_ambiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status_aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='FotoStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria_staff/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_fotos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
