# Generated by Django 6.1 on 2026-08-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 1.75', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='categoria_cnh',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cor_cabelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idiomas',
            field=models.CharField(blank=True, help_text='Ex: Inglês, Espanhol', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_blacklist',
            field=models.BooleanField(default=False, verbose_name='Bloqueado na Blacklist'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Destaque VIP'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivo_blacklist',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Bloqueio Interno'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='possui_cnh',
            field=models.BooleanField(default=False),
        ),
    ]
