# Generated by Django 6.1 on 2026-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_altura_usuario_categoria_cnh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idiomas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
