# Generated by Django 6.1 on 2026-09-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_empresa_limite_staffs_fotostaff_is_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cor_fundo',
            field=models.CharField(default='#080605', max_length=7, verbose_name='Cor de Fundo (Hex)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_primaria',
            field=models.CharField(default='#A2673B', max_length=7, verbose_name='Cor Primária (Hex)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_secundaria',
            field=models.CharField(default='#1C0D07', max_length=7, verbose_name='Cor Secundária (Hex)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo da Empresa'),
        ),
    ]
