# Generated by Django 6.1 on 2026-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_empresa_cor_fundo_empresa_cor_primaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_eventos_mes',
            field=models.IntegerField(default=10, verbose_name='Limite de Eventos por Mês'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='recurso_checkin_gps',
            field=models.BooleanField(default=True, verbose_name='Módulo Check-in GPS'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='recurso_exportacao_pix',
            field=models.BooleanField(default=True, verbose_name='Módulo Lote PIX (CSV)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='recurso_nfse',
            field=models.BooleanField(default=False, verbose_name='Módulo Emissão NFS-e'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='recurso_portal_cliente',
            field=models.BooleanField(default=True, verbose_name='Módulo Portal do Cliente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='recurso_post_event_pdf',
            field=models.BooleanField(default=True, verbose_name='Módulo Relatório Post-Event PDF'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='recurso_whatsapp_api',
            field=models.BooleanField(default=False, verbose_name='Módulo Disparos WhatsApp'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='plano',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('PREMIUM', 'Premium'), ('CUSTOM', 'Personalizado / Enterprise')], default='BASICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('BLOQUEADO', 'Bloqueado'), ('SUSPENSO', 'Inadimplente / Suspenso')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('NAO_BINARIO', 'Não-binário'), ('OUTRO', 'Outro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (Dev)'), ('ADMIN', 'Admin Produtora'), ('STAFF', 'Staff / Colaborador')], default='STAFF', max_length=20),
        ),
    ]
