# Generated by Django 6.1 on 2026-09-01 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_empresa_limite_eventos_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario_afetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_sofridos', to=settings.AUTH_USER_MODEL)),
                ('usuario_executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_executados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
